import bcrypt from 'bcrypt';
import {PrismaBetterSqlite3} from '@prisma/adapter-better-sqlite3';
import {PrismaClient} from '../lib/generated/prisma/client.ts';
const db=new PrismaClient({adapter:new PrismaBetterSqlite3({url:'file:./dev.db'})});
const photos=['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85'];
const facilities=['Parking','WiFi','Air conditioning','Lift','Power backup','24/7 security','Gym','Water supply','Pet friendly','Balcony','CCTV','Clubhouse'];
const propertyData=[['Sea Breeze Residence','A sunlit home with calm interiors, generous balconies and quick access to the Bandra promenade.','24 Turner Road','Mumbai','Bandra West','400050',85000,250000,'APARTMENT',3,3,1650,'FULLY_FURNISHED'],['Aundh Garden House','A quiet independent home set beside mature trees, with a private terrace and dedicated parking.','18 DP Road','Pune','Aundh','411007',46000,120000,'INDEPENDENT_HOUSE',3,3,1900,'SEMI_FURNISHED'],['Indiranagar Loft','Contemporary loft living close to cafés and the metro, with warm wood finishes and ample daylight.','100 Feet Road','Bengaluru','Indiranagar','560038',52000,150000,'STUDIO',1,1,780,'FULLY_FURNISHED'],['Palm Court Villa','A refined family villa with a private garden, generous entertaining spaces and a peaceful lane.','Sindhu Bhavan Road','Ahmedabad','Bodakdev','380054',68000,200000,'VILLA',4,4,2800,'SEMI_FURNISHED'],['Koregaon Park Studio','A thoughtfully planned studio with hotel-like amenities, ideal for a working professional.','North Main Road','Pune','Koregaon Park','411001',29000,60000,'STUDIO',1,1,520,'FULLY_FURNISHED'],['Whitefield Skyhome','High-floor apartment with skyline views, a large clubhouse and easy access to the IT corridor.','ECC Road','Bengaluru','Whitefield','560066',44000,130000,'APARTMENT',2,2,1240,'SEMI_FURNISHED'],['Powai Lakeview','A polished residence with lake views, elegant common areas and excellent neighbourhood conveniences.','Central Avenue','Mumbai','Powai','400076',72000,210000,'APARTMENT',2,2,1380,'FULLY_FURNISHED'],['Satellite Family Home','A spacious, practical home near schools and everyday shopping with excellent natural ventilation.','Jodhpur Cross Road','Ahmedabad','Satellite','380015',32000,80000,'APARTMENT',3,2,1500,'UNFURNISHED'],['Hauz Khas Courtyard','Character-filled independent floor with a leafy courtyard and a short walk to the village market.','Aurobindo Marg','New Delhi','Hauz Khas','110016',78000,200000,'INDEPENDENT_HOUSE',3,3,1750,'SEMI_FURNISHED'],['Hitech City Executive PG','Premium managed accommodation with housekeeping, high-speed internet and all utilities included.','Botanical Garden Road','Hyderabad','Kondapur','500084',18000,36000,'PG',1,1,340,'FULLY_FURNISHED'],['Alwarpet Urban Nest','A serene apartment in a central neighbourhood, finished with understated contemporary details.','TTK Road','Chennai','Alwarpet','600018',56000,150000,'APARTMENT',3,3,1600,'SEMI_FURNISHED'],['Golf Course Work Loft','A flexible commercial studio with excellent frontage, meeting space and rapid metro connectivity.','Golf Course Road','Gurugram','Sector 54','122011',95000,285000,'COMMERCIAL',0,2,1400,'FULLY_FURNISHED']] as const;
const addMonths=(date:Date,count:number)=>new Date(date.getFullYear(),date.getMonth()+count,1,12);
async function main(){
  await db.reminder.deleteMany();await db.notification.deleteMany();await db.payment.deleteMany();await db.tenancy.deleteMany();await db.requestStatusHistory.deleteMany();await db.rentalRequest.deleteMany();await db.savedProperty.deleteMany();await db.propertyAvailabilityHistory.deleteMany();await db.propertyImage.deleteMany();await db.property.deleteMany();await db.user.deleteMany();
  const now=new Date(),year=now.getFullYear(),hash=await bcrypt.hash('Demo@123',12);
  const owner=await db.user.create({data:{name:'Arjun Mehta',email:'owner@demo.com',phone:'9876543210',passwordHash:hash,role:'OWNER'}}),owner2=await db.user.create({data:{name:'Priya Shah',email:'priya.owner@demo.com',phone:'9820012345',passwordHash:hash,role:'OWNER'}}),tenant=await db.user.create({data:{name:'Rohan Iyer',email:'tenant@demo.com',phone:'9988776655',passwordHash:hash,role:'TENANT'}}),tenant2=await db.user.create({data:{name:'Ananya Rao',email:'ananya@demo.com',phone:'9765432109',passwordHash:hash,role:'TENANT'}}),tenant3=await db.user.create({data:{name:'Kabir Singh',email:'kabir@demo.com',phone:'9876501234',passwordHash:hash,role:'TENANT'}});
  const properties:Awaited<ReturnType<typeof db.property.create>>[]=[];
  for(let i=0;i<propertyData.length;i++){const p=propertyData[i],occupied=[0,5,6].includes(i);properties.push(await db.property.create({data:{ownerId:i<7?owner.id:owner2.id,title:p[0],description:p[1],address:p[2],city:p[3],locality:p[4],pincode:p[5],monthlyRent:p[6],securityDeposit:p[7],type:p[8],bedrooms:p[9],bathrooms:p[10],areaSqFt:p[11],furnishing:p[12],facilities:JSON.stringify(facilities.slice(i%4,8+(i%4))),availability:occupied?'OCCUPIED':'AVAILABLE',availableFrom:occupied?null:addMonths(now,i%3),images:{create:[{url:photos[i%photos.length],alt:p[0],sortOrder:0},{url:photos[(i+2)%photos.length],alt:`${p[0]} interior`,sortOrder:1}]},availabilityHistory:{create:{availability:occupied?'OCCUPIED':'AVAILABLE',reason:occupied?'Active demo tenancy':'Property listed'}}}}));}
  const request=async(code:string,propertyId:string,tenantId:string,status:'SUBMITTED'|'APPROVED'|'REJECTED'|'CLOSED',move:Date,message:string,note?:string)=>db.rentalRequest.create({data:{requestCode:code,propertyId,tenantId,status,moveInDate:move,leaseMonths:12,occupants:status==='APPROVED'?2:1,message,ownerNote:note,createdAt:addMonths(now,-10),history:{create:status==='SUBMITTED'?[{status:'SUBMITTED',note:'Request submitted'}]:[{status:'SUBMITTED',note:'Request submitted',createdAt:addMonths(now,-10)},{status,note:note??`Request ${status.toLowerCase()}`,createdAt:addMonths(now,-9)}]}}});
  const req1=await request(`RR-${year}-00001`,properties[0].id,tenant.id,'APPROVED',addMonths(now,-11),'We are a working couple looking for a well-kept long-term home.','Documents verified');
  const req2=await request(`RR-${year}-00002`,properties[5].id,tenant2.id,'APPROVED',addMonths(now,-8),'I am relocating to Bengaluru and would like a long-term lease.','Welcome to Whitefield Skyhome');
  const req3=await request(`RR-${year}-00003`,properties[6].id,tenant3.id,'APPROVED',addMonths(now,-5),'I am looking for a quiet home close to work.','Approved after verification');
  const dueToday=Math.min(28,Math.max(1,now.getDate())),upcoming=Math.min(28,now.getDate()+3);
  const t1=await db.tenancy.create({data:{propertyId:properties[0].id,tenantId:tenant.id,requestId:req1.id,startDate:addMonths(now,-11),monthlyRent:85000,rentDueDay:dueToday,gracePeriodDays:3,active:true}}),t2=await db.tenancy.create({data:{propertyId:properties[5].id,tenantId:tenant2.id,requestId:req2.id,startDate:addMonths(now,-8),monthlyRent:44000,rentDueDay:upcoming,gracePeriodDays:3,active:true}}),t3=await db.tenancy.create({data:{propertyId:properties[6].id,tenantId:tenant3.id,requestId:req3.id,startDate:addMonths(now,-5),monthlyRent:72000,rentDueDay:20,gracePeriodDays:2,active:true}});
  const endedReq1=await request(`RR-${year}-00004`,properties[1].id,tenant2.id,'CLOSED',addMonths(now,-12),'Looking for a family home near work.','Tenancy completed');
  const endedReq2=await request(`RR-${year}-00005`,properties[3].id,tenant3.id,'CLOSED',addMonths(now,-9),'Our family needs a spacious villa.','Tenancy completed');
  const ended1=await db.tenancy.create({data:{propertyId:properties[1].id,tenantId:tenant2.id,requestId:endedReq1.id,startDate:addMonths(now,-12),endDate:addMonths(now,-6),monthlyRent:46000,rentDueDay:5,gracePeriodDays:3,active:false}}),ended2=await db.tenancy.create({data:{propertyId:properties[3].id,tenantId:tenant3.id,requestId:endedReq2.id,startDate:addMonths(now,-9),endDate:addMonths(now,-3),monthlyRent:68000,rentDueDay:7,gracePeriodDays:2,active:false}});
  await db.propertyAvailabilityHistory.createMany({data:[{propertyId:properties[1].id,availability:'OCCUPIED',reason:'Rental request approved',createdAt:addMonths(now,-12)},{propertyId:properties[1].id,availability:'AVAILABLE',reason:'Tenancy ended',createdAt:addMonths(now,-6)},{propertyId:properties[3].id,availability:'OCCUPIED',reason:'Rental request approved',createdAt:addMonths(now,-9)},{propertyId:properties[3].id,availability:'AVAILABLE',reason:'Tenancy ended',createdAt:addMonths(now,-3)}]});
  let receipt=1;const paymentRows:{receiptCode:string;tenancyId:string;month:number;year:number;amount:number;paymentDate:Date;method:'UPI'|'BANK_TRANSFER'|'CASH'|'CHEQUE';transactionRef:string}[]=[];
  const addHistory=(tenancy:{id:string;startDate:Date;endDate:Date|null;monthlyRent:number;rentDueDay:number},months:number,skip:number[])=>{for(let back=months;back>=1;back--){if(skip.includes(back))continue;const d=addMonths(now,-back);if(d<tenancy.startDate||(tenancy.endDate&&d>tenancy.endDate))continue;const late=back%4===0?6:back%5===0?2:0;paymentRows.push({receiptCode:`PAY-${d.getFullYear()}-${String(receipt++).padStart(5,'0')}`,tenancyId:tenancy.id,month:d.getMonth()+1,year:d.getFullYear(),amount:tenancy.monthlyRent,paymentDate:new Date(d.getFullYear(),d.getMonth(),tenancy.rentDueDay+late,12),method:back%4===0?'BANK_TRANSFER':back%3===0?'CASH':'UPI',transactionRef:`RN${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${receipt}`})}};
  addHistory(t1,11,[7]);addHistory(t2,8,[4]);addHistory(t3,5,[1]);addHistory(ended1,12,[9]);addHistory(ended2,9,[6]);await db.payment.createMany({data:paymentRows});
  const pending=await request(`RR-${year}-00006`,properties[2].id,tenant2.id,'SUBMITTED',addMonths(now,1),'I am relocating to Bengaluru for work and love this neighbourhood.');await request(`RR-${year}-00007`,properties[4].id,tenant3.id,'REJECTED',addMonths(now,1),'I would like a six-month stay near my office.','Move-in schedule did not align.');await request(`RR-${year}-00008`,properties[8].id,tenant.id,'CLOSED',addMonths(now,1),'Interested in this character-filled home.','Withdrawn by tenant');
  await db.savedProperty.createMany({data:[{userId:tenant.id,propertyId:properties[8].id},{userId:tenant.id,propertyId:properties[10].id},{userId:tenant2.id,propertyId:properties[1].id}]});
  await db.notification.createMany({data:[{userId:tenant.id,tenancyId:t1.id,month:`${year}-${String(now.getMonth()+1).padStart(2,'0')}`,type:'RENT_DUE',title:'Rent due today',message:`Your rent of ₹85,000 for ${now.toLocaleString('en-IN',{month:'long'})} is due today.`,link:'/tenant/payments',isRead:false},{userId:owner.id,tenancyId:t3.id,type:'RENT_OVERDUE',title:'Overdue rent · Powai Lakeview',message:'Kabir’s previous month rent is overdue.',link:'/owner/calendar',isRead:false},{userId:tenant.id,type:'REQUEST_APPROVED',title:'Welcome home',message:'Your Sea Breeze Residence tenancy is active.',link:`/requests/${req1.id}`,isRead:true},{userId:owner.id,type:'REQUEST_APPROVED',title:'New rental request',message:`${pending.requestCode} is waiting for your review.`,link:`/requests/${pending.id}`,isRead:false},{userId:tenant2.id,tenancyId:t2.id,type:'RENT_UPCOMING',title:'Rent due soon',message:`Your Whitefield Skyhome rent is due in three days.`,link:'/tenant/payments',isRead:false}]});
  console.log(`Seeded ${properties.length} properties, ${paymentRows.length} payments, due reminders and 12-month analytics. Pending request: ${pending.requestCode}`);
}
main().finally(()=>db.$disconnect());
