'use client';
import Link from 'next/link';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {Bell,CheckCheck} from 'lucide-react';
import {toast} from 'sonner';
import {markAllNotificationsReadAction} from '@/server/actions/notifications';
import {Button} from '@/components/ui/button';
type Notice={id:string;title:string;message:string;link:string|null;isRead:boolean;createdAt:string};
export function NotificationBell({notifications}: {notifications:Notice[]}){const[open,setOpen]=useState(false);const[pending,start]=useTransition();const router=useRouter();const unread=notifications.filter(n=>!n.isRead).length;return <div className="relative"><Button size="icon" variant="ghost" aria-label={`${unread} unread notifications`} onClick={()=>setOpen(!open)}><Bell className="size-4"/>{unread>0&&<span className="absolute right-1 top-1 grid size-4 place-items-center rounded-full bg-red-500 text-[10px] font-bold text-white">{Math.min(9,unread)}</span>}</Button>{open&&<><button className="fixed inset-0 z-40" aria-label="Close notifications" onClick={()=>setOpen(false)}/><div className="absolute right-0 z-50 mt-2 w-[min(360px,calc(100vw-2rem))] overflow-hidden rounded-xl border bg-background shadow-2xl"><div className="flex items-center justify-between border-b p-4"><div><p className="font-semibold">Notifications</p><p className="text-xs text-muted-foreground">{unread} unread</p></div><button disabled={pending||!unread} className="flex items-center gap-1 text-xs font-semibold text-primary disabled:opacity-40" onClick={()=>start(async()=>{const r=await markAllNotificationsReadAction();if(r.success){toast.success(r.message);router.refresh()}})}><CheckCheck className="size-4"/>Mark all read</button></div><div className="max-h-80 overflow-y-auto">{notifications.slice(0,5).map(n=><Link key={n.id} href={n.link??'/notifications'} onClick={()=>setOpen(false)} className={`block border-b p-4 last:border-0 hover:bg-muted ${n.isRead?'':'bg-primary/5'}`}><div className="flex gap-2"><span className={`mt-1 size-2 shrink-0 rounded-full ${n.isRead?'bg-border':'bg-primary'}`}/><div><p className="text-sm font-semibold">{n.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{n.message}</p><p className="mt-1 text-[11px] text-muted-foreground">{new Date(n.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p></div></div></Link>)}{!notifications.length&&<p className="p-8 text-center text-sm text-muted-foreground">You’re all caught up.</p>}</div><Link href="/notifications" onClick={()=>setOpen(false)} className="block border-t p-3 text-center text-xs font-semibold text-primary">View all notifications</Link></div></>}</div>}

