'use client';
import {useActionState,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ImagePlus,Loader2} from 'lucide-react';
import {savePropertyAction} from '@/server/actions/properties';
import {FACILITIES,titleCase,type ActionResult} from '@/lib/utils';
import {Button} from './ui/button'; import {Input} from './ui/input'; import {Label} from './ui/label'; import {Textarea} from './ui/textarea';
type Initial={id?:string;title?:string;description?:string;address?:string;city?:string;locality?:string;pincode?:string;monthlyRent?:number;securityDeposit?:number;type?:string;bedrooms?:number;bathrooms?:number;areaSqFt?:number;furnishing?:string;facilities?:string[];availability?:string;availableFrom?:string};
const initialResult:ActionResult={success:false,error:''};
export function PropertyForm({initial={}}:{initial?:Initial}){
 const[result,action,pending]=useActionState(savePropertyAction,initialResult); const[step,setStep]=useState(0); const steps=['Basics','Location & rent','Home details','Facilities & photos'];
 return <form action={action} className="mx-auto max-w-4xl"><input type="hidden" name="id" value={initial.id}/>
  <div className="mb-7 grid grid-cols-4 gap-2">{steps.map((s,i)=><button type="button" onClick={()=>setStep(i)} key={s} className={`rounded-lg border p-3 text-left text-xs font-semibold transition ${i===step?'border-primary bg-primary/8 text-primary':'text-muted-foreground'}`}><span className="mb-1 block font-mono">0{i+1}</span>{s}</button>)}</div>
  <div className="rounded-xl border bg-card p-6 sm:p-8">
   <section className={step===0?'space-y-5':'hidden'}><StepTitle title="Tell us about the property" copy="Start with a clear title and an honest, helpful description."/><Field label="Property title"><Input name="title" defaultValue={initial.title} placeholder="e.g. Sunlit 2 BHK near Koregaon Park" required/></Field><Field label="Description"><Textarea name="description" defaultValue={initial.description} placeholder="Describe the home, surroundings, and what makes it a great place to live." className="min-h-40" required/></Field><Field label="Property type"><Select name="type" value={initial.type} options={['APARTMENT','INDEPENDENT_HOUSE','VILLA','PG','STUDIO','COMMERCIAL']}/></Field></section>
   <section className={step===1?'space-y-5':'hidden'}><StepTitle title="Location and monthly terms" copy="Give tenants enough context to understand the neighbourhood and costs."/><Field label="Street address"><Input name="address" defaultValue={initial.address} required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="City"><Input name="city" defaultValue={initial.city} required/></Field><Field label="Area / locality"><Input name="locality" defaultValue={initial.locality} required/></Field></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Pincode"><Input name="pincode" defaultValue={initial.pincode} inputMode="numeric" required/></Field><Field label="Monthly rent (₹)"><Input name="monthlyRent" defaultValue={initial.monthlyRent} type="number" required/></Field><Field label="Security deposit (₹)"><Input name="securityDeposit" defaultValue={initial.securityDeposit} type="number" required/></Field></div></section>
   <section className={step===2?'space-y-5':'hidden'}><StepTitle title="Home details" copy="Accurate details help tenants decide quickly."/><div className="grid gap-4 sm:grid-cols-3"><Field label="Bedrooms"><Input name="bedrooms" defaultValue={initial.bedrooms??1} type="number" min="0" required/></Field><Field label="Bathrooms"><Input name="bathrooms" defaultValue={initial.bathrooms??1} type="number" min="1" required/></Field><Field label="Area (sq ft)"><Input name="areaSqFt" defaultValue={initial.areaSqFt} type="number" required/></Field></div><Field label="Furnishing"><Select name="furnishing" value={initial.furnishing} options={['UNFURNISHED','SEMI_FURNISHED','FULLY_FURNISHED']}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Availability"><Select name="availability" value={initial.availability??'AVAILABLE'} options={['AVAILABLE','OCCUPIED']}/></Field><Field label="Available from"><Input name="availableFrom" defaultValue={initial.availableFrom} type="date"/></Field></div></section>
   <section className={step===3?'space-y-6':'hidden'}><StepTitle title="Facilities and photos" copy="Highlight useful amenities and add up to five clear images."/><fieldset><legend className="mb-3 text-sm font-medium">Facilities</legend><div className="flex flex-wrap gap-2">{FACILITIES.map(f=><label key={f} className="cursor-pointer"><input className="peer sr-only" name="facilities" value={f} type="checkbox" defaultChecked={initial.facilities?.includes(f)}/><span className="inline-flex rounded-full border px-3 py-2 text-sm peer-checked:border-primary peer-checked:bg-primary peer-checked:text-primary-foreground">{f}</span></label>)}</div></fieldset><label className="flex cursor-pointer flex-col items-center rounded-xl border border-dashed p-8 text-center hover:bg-muted"><ImagePlus className="size-8 text-primary"/><span className="mt-3 text-sm font-semibold">Add property images</span><span className="mt-1 text-xs text-muted-foreground">JPG, PNG or WebP, up to 5 MB each</span><input className="sr-only" type="file" name="images" accept="image/*" multiple/></label></section>
   {result.error&&<p className="mt-5 rounded-lg bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-300">{result.error}</p>}
   <div className="mt-8 flex justify-between border-t pt-5"><Button type="button" variant="outline" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft className="size-4"/>Back</Button>{step<3?<Button type="button" onClick={()=>setStep(s=>s+1)}>Continue<ArrowRight className="size-4"/></Button>:<Button disabled={pending}>{pending?<Loader2 className="size-4 animate-spin"/>:<Check className="size-4"/>}{initial.id?'Save changes':'Publish property'}</Button>}</div>
  </div>
 </form>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label>{children}</div>}
function StepTitle({title,copy}:{title:string;copy:string}){return <div className="mb-6"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div>}
function Select({name,value,options}:{name:string;value?:string;options:string[]}){return <select name={name} defaultValue={value} className="h-10 w-full rounded-md border bg-background px-3 text-sm">{options.map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select>}
