'use client';
import {useActionState} from 'react'; import {useForm} from 'react-hook-form'; import {zodResolver} from '@hookform/resolvers/zod'; import {z} from 'zod'; import {Check,Copy,Loader2} from 'lucide-react'; import {toast} from 'sonner';
import {createRentalRequestAction} from '@/server/actions/requests'; import {rentalRequestSchema} from '@/lib/validations'; import type {ActionResult} from '@/lib/utils'; import {Button} from './ui/button'; import {Input} from './ui/input'; import {Label} from './ui/label'; import {Textarea} from './ui/textarea';
type FormInput=z.input<typeof rentalRequestSchema>;type FormOutput=z.output<typeof rentalRequestSchema>;const initial:ActionResult<{code:string}>={success:false,error:''};
export function RequestForm({propertyId}:{propertyId:string}){
 const[result,action,pending]=useActionState(createRentalRequestAction,initial);const{register,formState:{errors}}=useForm<FormInput,unknown,FormOutput>({resolver:zodResolver(rentalRequestSchema),mode:'onBlur',defaultValues:{propertyId,leaseMonths:12,occupants:1,message:'',moveInDate:''}});
 if(result.success&&result.data)return <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/8 p-5"><Check className="size-6 text-emerald-600"/><h3 className="mt-3 font-semibold">Request submitted</h3><p className="mt-1 text-sm text-muted-foreground">Keep this request ID for your records.</p><button onClick={()=>{navigator.clipboard.writeText(result.data!.code);toast.success('Request ID copied')}} className="mt-4 flex items-center gap-3 rounded-lg border bg-background px-4 py-3 font-mono text-lg font-bold">{result.data.code}<Copy className="size-4"/></button></div>;
 return <form action={action} className="space-y-4"><input type="hidden" {...register('propertyId')}/><div><Label>Preferred move-in date</Label><Input type="date" required {...register('moveInDate')}/><Error text={errors.moveInDate?.message}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Lease duration</Label><Input type="number" min="1" max="60" required {...register('leaseMonths')}/><Error text={errors.leaseMonths?.message}/></div><div><Label>Occupants</Label><Input type="number" min="1" max="20" required {...register('occupants')}/><Error text={errors.occupants?.message}/></div></div><div><Label>Message to owner</Label><Textarea placeholder="Tell the owner a little about yourself and your rental needs…" required {...register('message')}/><Error text={errors.message?.message}/></div>{result.error&&<p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-300">{result.error}</p>}<Button className="w-full" size="lg" disabled={pending}>{pending&&<Loader2 className="size-4 animate-spin"/>}Send rental request</Button><p className="text-center text-xs text-muted-foreground">Your contact details are shared only with the property owner.</p></form>
}
function Error({text}:{text?:string}){return text?<p className="mt-1 text-xs text-red-600">{text}</p>:null}
