export type AnalyticsTenancy = { id:string; propertyId:string; startDate:Date; endDate:Date|null; monthlyRent:number; rentDueDay:number };
export type AnalyticsPayment = { tenancyId:string; month:number; year:number; amount:number; paymentDate:Date; method:string };
export type AnalyticsProperty = { id:string; title:string; city:string; type:string; createdAt:Date };
export type MonthMetric = { key:string; label:string; expected:number; collected:number; outstanding:number; collectionRate:number; occupancyRate:number; averageDaysLate:number };
const dayMs=86_400_000;
const startOfDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate(),12);
const overlapDays=(a:Date,b:Date,c:Date,d:Date)=>Math.max(0,Math.floor((Math.min(b.getTime(),d.getTime())-Math.max(a.getTime(),c.getTime()))/dayMs)+1);
export function analyticsMonths(count:number,end=new Date()){return Array.from({length:count},(_,i)=>{const d=new Date(end.getFullYear(),end.getMonth()-count+1+i,1);return d});}
export function tenancyActiveInMonth(t:AnalyticsTenancy,month:Date){const first=new Date(month.getFullYear(),month.getMonth(),1);const last=new Date(month.getFullYear(),month.getMonth()+1,0,23,59,59);return t.startDate<=last&&(!t.endDate||t.endDate>=first);}
export function calculateMonthlyMetrics(tenancies:AnalyticsTenancy[],payments:AnalyticsPayment[],properties:AnalyticsProperty[],months:Date[]):MonthMetric[]{return months.map(month=>{const active=tenancies.filter(t=>tenancyActiveInMonth(t,month));const monthPayments=payments.filter(p=>p.year===month.getFullYear()&&p.month===month.getMonth()+1);const expected=active.reduce((sum,t)=>sum+t.monthlyRent,0);const collected=monthPayments.reduce((sum,p)=>sum+p.amount,0);const first=new Date(month.getFullYear(),month.getMonth(),1,12);const last=new Date(month.getFullYear(),month.getMonth()+1,0,12);const days=last.getDate();const occupiedDays=properties.reduce((sum,p)=>sum+tenancies.filter(t=>t.propertyId===p.id).reduce((n,t)=>n+overlapDays(startOfDay(t.startDate),startOfDay(t.endDate??last),first,last),0),0);const late=monthPayments.map(p=>{const t=tenancies.find(x=>x.id===p.tenancyId);if(!t)return 0;const due=new Date(p.year,p.month-1,t.rentDueDay,12);return Math.max(0,Math.round((startOfDay(p.paymentDate).getTime()-due.getTime())/dayMs))});return{key:`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`,label:month.toLocaleString('en-IN',{month:'short',year:'2-digit'}),expected,collected,outstanding:Math.max(0,expected-collected),collectionRate:expected?Math.round(collected/expected*100):0,occupancyRate:properties.length?Math.min(100,Math.round(occupiedDays/(properties.length*days)*100)):0,averageDaysLate:late.length?Math.round(late.reduce((a,b)=>a+b,0)/late.length):0}})}
export function calculatePropertyMetrics(tenancies:AnalyticsTenancy[],payments:AnalyticsPayment[],properties:AnalyticsProperty[],months:Date[]){if(!months.length)return[];const rangeStart=new Date(months[0].getFullYear(),months[0].getMonth(),1,12);const lastMonth=months[months.length-1];const rangeEnd=new Date(lastMonth.getFullYear(),lastMonth.getMonth()+1,0,12);const totalDays=Math.floor((rangeEnd.getTime()-rangeStart.getTime())/dayMs)+1;return properties.map(property=>{const pts=tenancies.filter(t=>t.propertyId===property.id);const activeMonths=months.flatMap(m=>pts.filter(t=>tenancyActiveInMonth(t,m)));const expected=activeMonths.reduce((s,t)=>s+t.monthlyRent,0);const ids=new Set(pts.map(t=>t.id));const pp=payments.filter(p=>ids.has(p.tenancyId)&&months.some(m=>p.year===m.getFullYear()&&p.month===m.getMonth()+1));const collected=pp.reduce((s,p)=>s+p.amount,0);const occupiedDays=Math.min(totalDays,pts.reduce((s,t)=>s+overlapDays(startOfDay(t.startDate),startOfDay(t.endDate??rangeEnd),rangeStart,rangeEnd),0));const onTime=pp.filter(p=>{const t=pts.find(x=>x.id===p.tenancyId);return t&&p.paymentDate<=new Date(p.year,p.month-1,t.rentDueDay,23,59,59)}).length;return{propertyId:property.id,title:property.title,city:property.city,type:property.type,occupancyRate:Math.round(occupiedDays/totalDays*100),collected,outstanding:Math.max(0,expected-collected),onTimeRate:pp.length?Math.round(onTime/pp.length*100):0,vacancyDays:Math.max(0,totalDays-occupiedDays)}})}
export function groupRevenue(payments:AnalyticsPayment[],tenancies:AnalyticsTenancy[],properties:AnalyticsProperty[],by:'method'|'type'|'city'){const map=new Map<string,number>();for(const p of payments){const t=tenancies.find(x=>x.id===p.tenancyId);const property=properties.find(x=>x.id===t?.propertyId);const key=by==='method'?p.method:by==='type'?property?.type:property?.city;if(key)map.set(key,(map.get(key)??0)+p.amount)}return [...map].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
